version: "3.7"
services:
  db:
    image: postgres
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./django:/app/"
      - "./docker-entrypoint.sh:/docker-entrypoint/docker-entrypoint.sh"
    command: sh /docker-entrypoint/docker-entrypoint.sh  
    ports:
      - "8001:8001"
    depends_on:
      - db
  markdown-renderer:
    image: node:10.15.3
    working_dir: /code/
    volumes:
      - ./markdown-renderer:/code/
    ports:
      - 8005:8005
    environment: 
      - RENDER_FILE_LOCATION=/code/src/Resume.md
      - PORT=8005
    command: >
      bash -c 'npm install && npm start && rm -rf ./node_modules && echo "Cleared node_modules"'

  