# Docker-compose file for local development
version: "3.7"
services:
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=myhardpassword

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: sh /build/docker-entrypoint.dev.sh
    restart: always
    ports:
      - "80:8001"
    environment: 
      - DJANGO_IS_PRODUCTION=False
      - DJANGO_DEBUG=True
      - DJANGO_SITE_URL=dev.seemyresume.io
      - DJANGO_EMAIL_FILE_PATH=/sent_emails/
      - DB_DBNAME=postgres
      - DB_PASSWORD=myhardpassword
      - DB_USERNAME=postgres
      - DB_FQDN=db
      - DB_PORT=5432
      - ACTIVATE_GOOGLE_ANALYTICS=False
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
