# Docker-compose file for local development
version: "3.7"
services:
  db:
    image: postgres
  webapp:
    build:
      context: ./
      dockerfile: build/local/Dockerfile
    volumes:
      - "./webapp:/app/"
      - "./build/docker-entrypoint.dev.sh:/docker-entrypoint/docker-entrypoint.dev.sh"
      - "./build/wait-for-it.sh:/wait-for-it.sh"
    entrypoint: sh /docker-entrypoint/docker-entrypoint.dev.sh  
    ports:
      - "8001:8001"
    environment: 
      - DJANGO_SITE_URL=localhost
      - DJANGO_LOCAL_PORT=8001
    depends_on:
      - db
  webapp-tests:
    build:
      context: ./
      dockerfile: ./build/tests/Dockerfile
    volumes:
      - "./webapp:/app/"
      - "./build/docker-test-entrypoint.sh:/docker-entrypoint/docker-test-entrypoint.sh"
      - "./build/wait-for-it.sh:/wait-for-it.sh"
    entrypoint: sh /docker-entrypoint/docker-test-entrypoint.sh
    environment: 
      - DJANGO_SITE_URL=localhost:8001
      - DJANGO_EMAIL_FILE_PATH="/sent_emails/"
    depends_on:
      - db
