# Docker-compose file for local development
version: "3.7"
services:
  db:
    image: postgres
  webapp:
    build:
      context: ./
      dockerfile: build/local/Dockerfile
    volumes:
      - "./webapp:/app/"
      - "./build/local/docker-entrypoint.dev.sh:/docker-entrypoint/docker-entrypoint.dev.sh"
    entrypoint: sh /docker-entrypoint/docker-entrypoint.dev.sh  
    ports:
      - "8001:8001"
    depends_on:
      - db
      - markdown-renderer
  webapp-tests:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./webapp:/app/"
      - "./build/local/docker-test-entrypoint.sh:/docker-entrypoint/docker-test-entrypoint.sh"
      - "./build/wait-for-it.sh:/wait-for-it.sh"
    entrypoint: sh /docker-entrypoint/docker-test-entrypoint.sh
    depends_on:
      - db
  markdown-renderer:
    image: node:10.15.3
    working_dir: /code/
    volumes:
      - ./markdown-renderer:/code/
    ports:
      - 8005:8005
    environment: 
      - RENDER_FILE_LOCATION=/code/src/Resume.md
      - PORT=80
    command: >
      bash -c 'npm install && npm start && rm -rf ./node_modules && echo "Cleared node_modules"'

  