# Docker-compose file for serving on a development server
version: "3.7"
services:
  db:
    image: postgres
  webapp:
    build:
      context: ./
      dockerfile: build/dev/webapp.Dockerfile
    ports:
      - 80:8001
    environment: 
      - DJANGO_SITE_URL=dev.seemyresume.io
    depends_on:
      - db
      