# Docker-compose file for serving on a development server
version: "3.7"
services:
  db:
    image: postgres
  webapp:
    image: docker.pkg.github.com/android2221/resume-builder/resume-builder:develop
    ports:
      - "8001:8001"
    depends_on:
      - db
      - markdown-renderer
  markdown-renderer:
    image: docker.pkg.github.com/android2221/resume-builder/markdown-renderer:develop
    environment: 
      - RENDER_FILE_LOCATION=/code/src/Resume.md
      - PORT=5001
      