# Docker-compose file for local development
version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=myhardpassword
  webapp:
    build:
      context: ./
      dockerfile: build/local/Dockerfile
    volumes:
      - "./webapp:/app/"
      - "./build/docker-entrypoint.dev.sh:/docker-entrypoint/docker-entrypoint.dev.sh"
      - "./build/wait-for-it.sh:/wait-for-it.sh"
    entrypoint: sh /docker-entrypoint/docker-entrypoint.dev.sh  
    ports:
      - "80:8001"
    environment: 
      - DJANGO_SITE_URL=dev.seemyresume.io
      - DJANGO_EMAIL_FILE_PATH=/sent_emails/
      - POSTGRES_PASSWORD=myhardpassword
    depends_on:
      - db
