version: "3.7"
services:
  db:
    image: postgres
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./src:/app/"
      - "./docker-entrypoint.sh:/docker-entrypoint/docker-entrypoint.sh"
    command: sh /docker-entrypoint/docker-entrypoint.sh  
    ports:
      - "8001:8001"
    depends_on:
      - db

  