# Docker-compose file for serving on a development server
version: "3.7"
services:
  db:
    image: postgres
  webapp:
    build:
      context: ./
      dockerfile: build/dev/webapp.Dockerfile
    ports:
      - 80:8001
    environment: 
      - DJANGO_SITE_URL=localhost
      - MARKDOWN_SITE_URL=http://markdown-renderer:5001/
    depends_on:
      - db
      - markdown-renderer
  markdown-renderer:
    build:
      context: ./
      dockerfile: build/dev/markdown-renderer.Dockerfile
    environment: 
      - PORT=5001
      