# Docker-compose file for local development
version: "3.7"
services:
  db:
    image: postgres
  webapp:
    build:
      context: ./
      dockerfile: build/local/Dockerfile
    volumes:
      - "./webapp:/app/"
      - "./build/docker-entrypoint.dev.sh:/docker-entrypoint/docker-entrypoint.dev.sh"
      - "./build/wait-for-it.sh:/wait-for-it.sh"
    entrypoint: sh /docker-entrypoint/docker-entrypoint.dev.sh  
    ports:
      - "8001:8001"
    environment: 
      - DJANGO_SITE_URL=localhost
      - DJANGO_LOCAL_PORT=8001
      - MARKDOWN_SITE_URL=http://markdown-renderer:5001/
    depends_on:
      - db
      - markdown-renderer
  webapp-tests:
    build:
      context: ./
      dockerfile: ./build/tests/Dockerfile
    volumes:
      - "./webapp:/app/"
      - "./build/docker-test-entrypoint.sh:/docker-entrypoint/docker-test-entrypoint.sh"
      - "./build/wait-for-it.sh:/wait-for-it.sh"
    entrypoint: sh /docker-entrypoint/docker-test-entrypoint.sh
    environment: 
      - DJANGO_SITE_URL=localhost:8001
      - DJANGO_EMAIL_FILE_PATH="/sent_emails/"
      - MARKDOWN_SITE_URL=http://markdown-renderer:5001/
    depends_on:
      - db
  markdown-renderer:
    image: node:10.15.3
    working_dir: /code/
    volumes:
      - ./markdown-renderer:/code/
    environment: 
      - PORT=5001
    command: >
      bash -c 'npm install && npm start && rm -rf ./node_modules && echo "Cleared node_modules"'

  