# Docker-compose file for local development
version: "3.7"
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["uwsgi", "--shared-socket", "0.0.0.0:8443", "--uid", "appuser", "--gid", "appuser", "--https", "=0,/certs/cert.pem,/certs/privkey.pem"]
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - "/etc/letsencrypt/live/seemyresume.io/cert.pem:/certs/cert.pem"
      - "/etc/letsencrypt/live/seemyresume.io/privkey.pem:/certs/privkey.pem"
    env_file:
      - ./env-vars.env
    restart: always
    environment: 
      - SECURE_SSL_REDIRECT=True
      - SESSION_COOKIE_SECURE=True
      - CSRF_COOKIE_SECURE=True
      - ACTIVATE_GOOGLE_ANALYTICS=True
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
