name: CI
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'root@dev.seemyresume.io'
        privateKey: ${{ secrets.DEV_WEBSERVER_SSH_PRIVATE_KEY }}
        command: ls -lah
