name: CI
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to DEV
      uses: appleboy/ssh-action@master
      with:
        username: 'root'
        host: 'dev.seemyresume.io'
        key: ${{ secrets.DEV_WEBSERVER_SSH_KEY }}
        script: 'ls /'
