name: deploy-prod
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: seemyresume.io
          username: root
          key: ${{ secrets.PROD_WEBSERVER_SSH_PRIVATE_KEY }}
          script: "cd /app/resume-builder/ \
          && git checkout master \
          && git fetch --all \
          && git reset --hard origin/master \
          && docker-compose -f ./docker-compose.prod.yaml build \
          && docker-compose -f ./docker-compose.prod.yaml up -d"
